services:
  # nginx:
  #   build:
  #     context: requirements/nginx
  #     dockerfile: Dockerfile
  #   container_name: nginx
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/config.conf
  #   env_file:
  #     - .env
  #   environment:
  #     DOMAIN_NAME: ${DOMAIN_NAME}
  #     HOSTNAME: ${HOSTNAME}
  #   depends_on:
  #     - wordpress
  #   networks:
  #     - Inception42
  #   restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      secrets:
        - credentials
    container_name: wordpress
    volumes:
      - wp-vol:/var/www/html
      - wp-vol:/etc/php/7.4/fpm/pool.d/www.conf
    networks:
      - private
      - Inception42
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    environment:
      TABLE_PREFIX: wp_

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
      secrets:
        - db_root_pass
        - db_user_pass
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_TCP_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - private
    restart: unless-stopped
    stdin_open: true
    tty: true
    privileged: true
    security_opt:
      - no-new-privileges 
    cap_add:
      - SYS_ADMIN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    healthcheck:
      test: ["CMD-SHELL", "nc -zv 127.0.0.1 ${DB_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5


secrets:
  db_root_pass:
    file: ../secrets/db_root_password.txt
  db_user_pass:
    file: ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt
  # ftp_user_pass:
  #   file: ../secrets/ftp_user_pass.txt

volumes:
  db-vol:
    name: dataBase
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MARIADB_VOLUME}

  wp-vol:
    name: userData
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORDPRESS_VOLUME}

networks:
  Inception42:
    name: ${NETWORK_NAME}
    driver: bridge
  private:
    # ipam:
    #   config:
    #     - subnet: "10.0.0.0/19"
    #       gateway: "10.0.0.1"
