services:
  # nginx:
  #   build:
  #     context: requirements/nginx
  #     dockerfile: Dockerfile
  #   container_name: nginx
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/config.conf
  #   env_file:
  #     - .env
  #   environment:
  #     DOMAIN_NAME: ${DOMAIN_NAME}
  #     HOSTNAME: ${HOSTNAME}
  #   depends_on:
  #     - wordpress
  #   networks:
  #     - Inception42
  #   restart: always

  # wordpress:
  #   build: requirements/wordpress
  #   container_name: wordpress
  #   environment:
  #     WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
  #     WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
  #     WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  #     WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
  #     WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX:-wp_}
  #     WORDPRESS_DEBUG: ${WP_DEBUG:-0}
  #     WORDPRESS_CONFIG_EXTRA: |
  #       define('WP_HOME', 'http://${DOMAIN_NAME}');
  #       define('WP_SITEURL', 'http://${DOMAIN_NAME}');
  #   volumes:
  #     - wp-vol:/var/www/html
  #   env_file:
  #     - .env
  #   networks:
  #     - private
  #     - Inception42
  #   depends_on:
  #     - mariadb
  #   restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
      secrets:
        - db_root_pass
        - db_user_pass
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_TCP_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - private
    restart: always
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    # healthcheck:
    #   test: ["CMD-SHELL", "mysqladmin ping -h localhost -u example -pexample"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

secrets:
  db_root_pass:
    file: ../secrets/db_root_password.txt
  db_user_pass:
    file: ../secrets/db_password.txt
  wp_admin_pass:
    file: ../secrets/wp_admin_pass.txt
  wp_user_pass:
    file: ../secrets/wp_user_pass.txt
  ftp_user_pass:
    file: ../secrets/ftp_user_pass.txt
  credentials:
    file: ../secrets/credentials.txt

volumes:
  db-vol:
    name: dataBase
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MARIADB_VOLUME}

  wp-vol:
    name: userData
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORDPRESS_VOLUME}

networks:
  Inception42:
    name: ${NETWORK_NAME}
    driver: bridge
  private:
    # ipam:
    #   config:
    #     - subnet: "10.0.0.0/19"
    #       gateway: "10.0.0.1"

#  configs:
#    mariadbConfig:
#      file: ./requirements/mariadb/conf/config.cnf