
services:
  # nginx:
  #   build:
  #     context: requirements/nginx
  #     dockerfile: Dockerfile
  #   container_name: ${CONTAINER_NAME}_nginx
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/config.conf
  #   env_file:
  #     - .env
  #   environment:
  #     DOMAIN_NAME: ${DOMAIN_NAME}
  #     HOSTNAME: ${HOSTNAME}
  #   depends_on:
  #     - wordpress
  #   networks:
  #     - Inception42
  #   restart: always
# WORDPRESS
#   wordpress:
#     build: requirements/wordpress
#     container_name: ${CONTAINER_NAME}_wordpress
#     environment:
#       WORDPRESS_DB_HOST: ${WP_DB_HOST}
#       WORDPRESS_DB_USER: ${WP_DB_USER}
#       WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
#       WORDPRESS_DB_NAME: ${WP_DB_NAME}
#       WORDPRESS_TABLE_PREFIX: wp_
#       WORDPRESS_DEBUG: 1
#     volumes:
#       - wp-data:/var/www/html
#     env_file:
#       - .env
#     networks:
#       - private
#       - Inception42
#     depends_on:
#       - mariadb
#     restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}_mariadb
    # configs:
    #   - source: mariadbConfig
    #     target: /etc/mysql/mariadb.conf.d/config.cnf
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pass
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_pass
      MYSQL_TCP_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db-vol:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_user_pass
      - source: db_user_pass
        target: /run/secrets/db_root_pass
    networks:
      - private
    restart: always

volumes:
  db-vol:
    name: dataBase
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_VOLUME}

  wp-vol:
    name: userData
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WP_VOLUME}


networks:
  Inception42:
    name: ${NETWORK_NAME}
    driver: bridge
  private:
    # ipam:
    #   config:
    #     - subnet: "10.0.0.0/19"
    #       gateway: "10.0.0.1"
secrets:
  db_root_pass:
    file: ../secrets/db_root_password.txt
  db_user_pass:
    file: ../secrets/db_password.txt
  wp_admin_pass:
    file: ../secrets/wp_admin_pass.txt
  wp_user_pass:
    file: ../secrets/wp_user_pass.txt
  ftp_user_pass:
    file: ../secrets/ftp_user_pass.txt
  credentials:
    file: ../secrets/credentials.txt

#  configs:
#    mariadbConfig:
#      file: ./requirements/mariadb/conf/config.cnf


