GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'ROOT_PASSWORD_PLACEHOLDER';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS DATABASE_NAME_PLACEHOLDER;
CREATE USER IF NOT EXISTS 'USER_NAME_PLACEHOLDER'@'%' IDENTIFIED BY 'USER_PASSWORD_PLACEHOLDER';
GRANT ALL PRIVILEGES ON DATABASE_NAME_PLACEHOLDER.* TO 'USER_NAME_PLACEHOLDER'@'%';
FLUSH PRIVILEGES;

USE DATABASE_NAME_PLACEHOLDER;
CREATE TABLE info (name VARCHAR(255), level INT);
INSERT INTO info (name, level) VALUES ('USER_NAME_PLACEHOLDER', 6);